### ISSUE TITLE
About the node feature of Mutagenicity.

### ISSUE THREAD

**Issue by wOvOpy** [mertkosan/GCFExplainer#1]
Hi,
I have been working with the Mutagenicity data in the data.py file and I have encountered a problem. The number of node class is set at 10, and I am attempting to visualize the graph. However, I am uncertain how the node features correspond to the different node types. I would greatly appreciate your prompt response on this matter.

**Comment by mertkosan** [comment]
Hi wOvOpy,

Very good point and thanks for your question. In the Mutagenicity dataset, each node corresponds to an atom. Node labels are encoded as one-hot encoding. The original node mapping has 14 classes:

{0: 'C', 1: 'O', 2: 'Cl', 3: 'H', 4: 'N', 5: 'F', 6: 'Br', 7: 'S', 8: 'P', 9: 'I', 10: 'Na', 11: 'K', 12: 'Li', 13: 'Ca'}

However, as we mention in the code, we remove graphs if they include node classes that have a frequency less than or equal to 50. You can find the information on which atoms we kept in the "atoms_to_keep" variable, as I am not sure right now. However, I can add comments to the code soon.

Hope this helps. Let us know if you have more questions.

**Comment by wOvOpy** [comment]
thanks!
